
"use strict";
const {evaluateSymbol}=require("./decisionEngine");
function sliceIndexBars(indexBars,end){const o={};for(const k of Object.keys(indexBars||{}))o[k]=(indexBars[k]||[]).slice(0,end);return o}
function simulateTrade(signal,future,maxHold=10){if(!future?.length||!signal.stopLoss||!signal.target1||!signal.price)return null;const entry=Number(signal.price),stop=Number(signal.stopLoss),target=Number(signal.target1),risk=entry-stop;if(!Number.isFinite(risk)||risk<=0)return null;for(let i=0;i<Math.min(maxHold,future.length);i++){const b=future[i];if(Number(b.low)<=stop)return{outcome:"LOSS",exit:stop,r:-1,holdDays:i+1};if(Number(b.high)>=target)return{outcome:"WIN",exit:target,r:(target-entry)/risk,holdDays:i+1}}const last=future[Math.min(maxHold,future.length)-1];const r=(Number(last.close)-entry)/risk;return{outcome:r>=0?"WIN":"LOSS",exit:Number(last.close),r,holdDays:Math.min(maxHold,future.length)}}
function backtestSymbol(symbol,bars,indexBars,options={}){const lookback=options.lookback||220,maxHold=options.maxHold||10,trades=[];for(let i=lookback;i<bars.length-maxHold;i++){const signal=evaluateSymbol({symbol,bars:bars.slice(0,i),indexBars:sliceIndexBars(indexBars,i),riskDollars:100});if(signal.decision==="ENTER_NOW"){const sim=simulateTrade(signal,bars.slice(i,i+maxHold),maxHold);if(sim)trades.push({symbol,date:bars[i-1].date,setupType:signal.setupType,marketRegime:signal.marketRegime,score:signal.score,riskReward:signal.riskReward,...sim})}}return trades}
function summarizeTrades(trades){const count=trades.length,wins=trades.filter(t=>t.r>0).length,totalR=trades.reduce((s,t)=>s+Number(t.r||0),0),gw=trades.filter(t=>t.r>0).reduce((s,t)=>s+t.r,0),gl=Math.abs(trades.filter(t=>t.r<=0).reduce((s,t)=>s+t.r,0));let eq=0,peak=0,dd=0;for(const t of trades){eq+=t.r;peak=Math.max(peak,eq);dd=Math.min(dd,eq-peak)}return{trades:count,wins,losses:count-wins,winRate:count?Number((wins/count*100).toFixed(2)):0,expectancyR:count?Number((totalR/count).toFixed(3)):0,totalR:Number(totalR.toFixed(2)),profitFactor:gl?Number((gw/gl).toFixed(2)):gw?99:0,maxDrawdownR:Number(dd.toFixed(2)),avgHoldDays:count?Number((trades.reduce((s,t)=>s+t.holdDays,0)/count).toFixed(1)):0}}
function groupExpectancy(trades){const g={};for(const t of trades){const k=t.setupType||"UNKNOWN";(g[k]||(g[k]=[])).push(t)}const o={};for(const k of Object.keys(g))o[k]=summarizeTrades(g[k]);return o}
function runBacktest({symbols,barsBySymbol,indexBars,options={}}){const all=[],bySymbol={};for(const s of symbols){const bars=barsBySymbol[s];if(!Array.isArray(bars)||bars.length<260)continue;const t=backtestSymbol(s,bars,indexBars,options);bySymbol[s]=summarizeTrades(t);all.push(...t)}all.sort((a,b)=>String(a.date).localeCompare(String(b.date)));return{ok:true,updatedAt:new Date().toISOString(),symbolsTested:symbols.length,summary:summarizeTrades(all),expectancyBySetup:groupExpectancy(all),bySymbol,recentTrades:all.slice(-50),allTrades:all}}
module.exports={runBacktest,summarizeTrades,groupExpectancy,simulateTrade};
