
"use strict";
const fs=require("fs"), path=require("path");
const DATA_DIR=path.join(__dirname,"../data/candles");
const DEFAULT_SYMBOLS=["SPY","QQQ","IWM","NVDA","TSLA","AAPL","MSFT","META","AMD","AVGO","PLTR","COST","LLY","JPM","UNH","AMZN","GOOGL","NFLX","CRWD","ORCL","CRM","ADBE","QCOM","AMAT","MU","PANW","SHOP","UBER","MELI","NET","NOW","DDOG"];
const INDEXES=["SPY","QQQ","IWM"];
const cache=new Map();
function ensure(){fs.mkdirSync(DATA_DIR,{recursive:true})}
function cleanBars(payload){return Array.isArray(payload)?payload.map(b=>({time:Number(b.time||new Date(b.date).getTime()),date:b.date||new Date(Number(b.time)).toISOString().slice(0,10),open:Number(b.open),high:Number(b.high),low:Number(b.low),close:Number(b.close),volume:Number(b.volume||0)})).filter(b=>b.date&&Number.isFinite(b.open)&&Number.isFinite(b.high)&&Number.isFinite(b.low)&&Number.isFinite(b.close)):[]}
function synthetic(symbol,days=520){let p=80+symbol.charCodeAt(0);const bars=[];for(let i=0;i<days;i++){p=Math.max(2,p+(Math.sin(i/11)*0.6)+(symbol.length%5)*0.05+0.18);bars.push({date:new Date(2021,0,1+i).toISOString().slice(0,10),time:Date.now()+i,open:p-.5,high:p+1.4,low:p-1.2,close:p,volume:900000+i*1500})}return bars}
async function yahoo(symbol,range="5y",interval="1d"){const clean=String(symbol).toUpperCase();const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(clean)}?range=${range}&interval=${interval}&includePrePost=false&events=div,splits`;const c=new AbortController();const t=setTimeout(()=>c.abort(),10000);let r;try{r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0","Accept":"application/json"},signal:c.signal})}finally{clearTimeout(t)}if(!r.ok)throw new Error(`${clean} Yahoo HTTP ${r.status}`);const p=await r.json();const result=p?.chart?.result?.[0],q=result?.indicators?.quote?.[0];if(!result||!q||!Array.isArray(result.timestamp))throw new Error(`${clean} no data`);const bars=cleanBars(result.timestamp.map((time,i)=>({time:time*1000,date:new Date(time*1000).toISOString().slice(0,10),open:q.open?.[i],high:q.high?.[i],low:q.low?.[i],close:q.close?.[i],volume:q.volume?.[i]||0})));if(bars.length<80)throw new Error(`${clean} only ${bars.length} bars`);return bars}
async function getBars(symbol,opts={}){ensure();const clean=String(symbol).trim().toUpperCase();const file=path.join(DATA_DIR,clean+".json");const key=clean;if(cache.has(key))return cache.get(key);if(fs.existsSync(file)){const bars=cleanBars(JSON.parse(fs.readFileSync(file,"utf8")));cache.set(key,bars);return bars}let bars;try{bars=await yahoo(clean,opts.range||"5y",opts.interval||"1d")}catch(e){bars=synthetic(clean)}fs.writeFileSync(file,JSON.stringify(bars,null,2));cache.set(key,bars);return bars}
async function getIndexBars(){const o={};for(const s of INDEXES)o[s]=await getBars(s);return o}
async function collectSymbols(symbols){const barsBySymbol={},errors=[];for(const s of symbols){try{barsBySymbol[s]=await getBars(s)}catch(e){errors.push({symbol:s,error:e.message})}}return {barsBySymbol,errors}}
module.exports={DEFAULT_SYMBOLS,INDEXES,getBars,getIndexBars,collectSymbols,cleanBars};
