
"use strict";
const fs=require("fs"),path=require("path");const {calculatePositionSize}=require("./riskEngine");const FILE=path.join(__dirname,"../data/paperAccount.json");
function def(){return{starting:5000,cash:5000,open:{},closed:[],alerts:[],equityCurve:[],createdAt:new Date().toISOString()}}
function load(){if(!fs.existsSync(FILE))return def();try{const a=JSON.parse(fs.readFileSync(FILE,"utf8"));return{...def(),...a,open:a.open||{},closed:a.closed||[],alerts:a.alerts||[],equityCurve:a.equityCurve||[]}}catch(e){return def()}}
function save(a){fs.mkdirSync(path.dirname(FILE),{recursive:true});fs.writeFileSync(FILE,JSON.stringify(a,null,2))}
function openValue(a){return Object.values(a.open||{}).reduce((s,p)=>s+Number(p.lastPrice||p.entry)*Number(p.shares||0),0)}
function equity(a){return Number(a.cash||0)+openValue(a)}
function alert(a,type,signal,details){const item={id:Date.now()+"-"+Math.random().toString(16).slice(2),type,symbol:signal.symbol,time:new Date().toISOString(),details};a.alerts.unshift(item);a.alerts=a.alerts.slice(0,100);return item}
function processSignals(signals,settings={}){const a=load(),alerts=[];const by={};signals.forEach(s=>by[s.symbol]=s);for(const sym of Object.keys(a.open)){const p=a.open[sym],s=by[sym];if(!s)continue;p.lastPrice=s.price;let reason="";if(Number(s.price)<=Number(p.stopLoss))reason="Stop hit";else if(Number(s.price)>=Number(p.target1))reason="Target hit";else if(s.decision==="AVOID")reason="Decision downgrade";if(reason){const proceeds=Number(p.shares)*Number(s.price),pnl=proceeds-Number(p.cost);a.cash+=proceeds;const closed={...p,exit:s.price,exitTime:new Date().toISOString(),exitReason:reason,pnl:Number(pnl.toFixed(2))};a.closed.unshift(closed);alerts.push(alert(a,"TRADE_EXITED",s,closed));delete a.open[sym]}}for(const s of signals){if(s.decision!=="ENTER_NOW"||a.open[s.symbol]||Object.keys(a.open).length>=(settings.maxOpen||5))continue;const sz=calculatePositionSize({equity:equity(a),riskPct:settings.riskPct||1,entry:s.price,stop:s.stopLoss,maxPositionPct:settings.maxPositionPct||20});if(!sz.shares||sz.positionValue>a.cash)continue;const pos={symbol:s.symbol,entry:s.price,shares:sz.shares,cost:sz.positionValue,stopLoss:s.stopLoss,target1:s.target1,target2:s.target2,score:s.score,setupType:s.setupType,expectancy:s.expectancy,riskReward:s.riskReward,entryTime:new Date().toISOString(),lastPrice:s.price,reason:s.summary};a.cash-=pos.cost;a.open[s.symbol]=pos;alerts.push(alert(a,"TRADE_TAKEN",s,pos))}a.equityCurve.push({time:new Date().toISOString(),equity:Number(equity(a).toFixed(2))});a.equityCurve=a.equityCurve.slice(-1000);save(a);return{account:a,alerts}}
module.exports={load,save,processSignals,equity,openValue};
